# version: '3.3' # for CentOS7
version: "3.9"
services:
  backend:
    build: ./back
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint:
      "java -jar /khedmatkar/demo-0.0.1-SNAPSHOT.jar"
    networks:
      - network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: khedmatkar
    networks:
      - network
    volumes:
      - psql-data:/var/lib/postgres/data
    restart: always
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - network
    depends_on:
      - db
      - backend

networks:
  network:

volumes:
  psql-data:

